### ISSUE TITLE
Model validation overhaul

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#1265]
It's time to give the model validation support and overlook and see what parts needs overhauling. This issue will only track what is needed and what has been done. Each change should be logged as a different issue and tracked in here
- [x] _Breaking Change_ Update `DataAnnotations` and `FluentValidation` packages so that they register all their required types using an application-registration. These packages should work without the use of the default bootstrapper auto-registration capabilities: See #1267
- [x] Remove the hard-coded factories of `IDataAnnotationsValidatorAdapter` and `IFluentAdapter` and make is so that they are registered using an application-registration and then resolved as ctor dependencies where ever they are required. This will make it easier to add custom validation rules. Add implementation -> automatically available -> super-duper-happy-path. See #1279 for Data Annotations changes and #1305 for fluent validation changes
- [x] _Breaking Change_ Pass in `NancyContext` to `IModelValidator.Validate(...)` to follow our "context everywhere"-ethos. See #1311 
- [x] _Breaking Change_ Look over `ModelValidationResult.Errors` and make it more user-friendly. It needs to have a good way to get a list of errors per field. This is to make it easier to connect it to a form etc. Possibly be able to return the data as `Dictionary<string, IEnumerable<string>>` where the string is the name of the property and the list is the validation error messages for that property. See #1318
- [x] The `DataAnnotations` project is missing an `DataAnnotationsValidatorAdapter` implementation for the `CompareAttribute`. See comment https://github.com/NancyFx/Nancy/issues/1265#issuecomment-26484280
- [x] _Breaking Change_ Revise the `ModelValidationRule` class and `IDataAnnotationsValidatorAdapter.GetRules(ValidationAttribute attribute, PropertyDescriptor descriptor)` implementations. The rules needs to be more friendly to consume from a client-side perspective. Something like a collection where the key is the member name and then a collection of applicable rules. The changes should be reflected on `ModelValidationDescriptor` and should probably be able to return something like `Dictionary<string, IEnumerable<ModelValidationRule>>`, where the string is the name of the property and the list contains the validation rules that should be enforced for that property. See #1314
- [x] Clean up the types in `Nancy.Validation` namespace. Make sure all types follow the code conventions and styles. Add missing XML comments to public types and members. See #1306
