### ISSUE TITLE
Migrate existing configuration endpoints to the unified configuration API

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2000]
As mentioned in #1999 once the new unified configuration API is implemented, we need to migrate the various configurations that we currently have implemented. This issue is intended to track the progress of that work. If you identify a place that needs updating, please let us know. Each of these should be handled as separate pull-requests so we can perform the migrations in a controlled fashion and split between multiple authors

Things that should be migrated

* [x] XmlSettings (pull-request #2115)
* [x] JsonSettings (pull-request #2124)
* [x] DiagnosticsConfiguration (Bootstrapper method) (pull-request #2012)
* [x] CryptographicConfiguration (Bootstrapper method)
* [ ] StaticConfiguration (@TheCodeJunkie WIP)
* [x] GenericFileResponse.SafePaths (@jchannon pull-request #2184)

**Probably will be in 2.x, but not in 2.0**
* [ ] NancyInternalConfiguration (possibly?)
* [ ] NancyConventions (static content, views, localization and so on)
* [ ] RazorConfiguration (`IRazorConfiguration` + *.config stuff)
* [ ] Mime type registrations (issue #877)
* [ ] Nancy.Hosting.Aspnet custom *.config handler

**Class naming**
- `[Word]Configuration` - for the configuration class
- `[Word]ConfigurationExtensions` - for the `INancyEnvironment` extension
- `Default[Word]ConfigurationProvider` - for the `INancyDefaultConfigurationProvider / NancyDefaultConfigurationProvider<T>` implementation

**Branch naming convention**: I suggest we use a naming convention for the branches for each of these migrations. My suggested convention is _configuration-migration-xxxxxxx_ where _xxxxxxx_ is the name of the feature that is being migrated.

**Comment by jchannon** [comment]
:+1:

**Comment by thecodejunkie** [comment]
Ping @NancyFx/most-valued-minions @NancyFx/owners these are all up-for-grabs, don't be shy :yum:

**Comment by thecodejunkie** [comment]
@NancyFx/most-valued-minions Feel free to pick stuff from the above list

**Comment by phillip-haydon** [comment]
It's long winded but I prefer `Default[Word]ConfigurationProvider` or `Default[Word]ConfigProvider` simply because `Default` implies to the user that it can be overridden.

**Comment by thecodejunkie** [comment]
Updated description to reflect what will be going into `2.0` and what will end up in subsequent `2.x` releases

**Comment by thecodejunkie** [comment]
We've done what we want to get done for 2.0. Closing this. We can come back if/when we decide to migrate more
