### ISSUE TITLE
v2 Requirements

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2160]
As @thecodejunkie has put in his [blog](http://thecodejunkie.com/2015/11/08/our-plans-for-nancy-1-x-and-beyond/) we have plans for v2 and we need to document what we **want** and **need** to achieve this goal. This will then lead onto CoreCLR #1959 compatibility

**NEED!**
- [ ] Unified configuration API #2000 
- [x] Replace internal TPL async code to `async\await` #2105
- [ ] Instance based AppDomainAssemblyTypeScanner #1846
- [x] Make all route handlers `async` by default #2199

**Comment by dorvan** [comment]
what about an internal deadlock fencing algorithm?

**Comment by khellang** [comment]
> what about an internal deadlock fencing algorithm?

What does this even mean? :confused:

**Comment by thecodejunkie** [comment]
I think this is a bit of a moving target which depends on the number of hours we get to put in. A couple of things that pops into mind are

* Swap out the default JSON serializer #2163 
* Overhaul model-binding (there are some kinks in here and I'd like to cache reflection stuff to boost performance)
* Look at providing a new route declaration syntax
* Implement something like `IModuleEnricher` concept to give you better control about instantiating various `NancyModule` implementations
* More documentations, samples, guides
* Look at @khellang 's spike for a new boostrapper
* Overhaul registrations (`IApplicationRegistrations`, `IRequestRegistrations` etc)
* TinyIoC changes (child container + PCL) that @grumpydev has flagged
* Improve the Diagnostics Dashboard (new UI + more info in there)
* Rewrite tracing 

There are some of the things that I've had on my radar for a long time and a lot of them should go into a new major, instead of a minor

**Comment by simosentissi** [comment]
are we thinking of keeping the documentation in github wiki? I am thinking readthedocs or readme.io would be of good UX benefits especially that the content can be driven from the same source as now ?

**Comment by phillip-haydon** [comment]
We have no plans to move the documentation from the wiki. I personally don't see any reason to move away from it.

**Comment by jchannon** [comment]
Should this be closed or updated?

**Comment by thecodejunkie** [comment]
:stuck_out_tongue_winking_eye:
