### ISSUE TITLE
Get Nancy compiling on dotnet54/dnxcore50

### ISSUE THREAD

**Issue by Yantrio** [NancyFx/Nancy#2220]
## Proposal
As part of the latest microsoft movement, it would be nice to get nancy working on the new dotnet environment. 
This was started with pull requests #2211 and #2212 to get things compiling using the project.json project system. Now we need to get some good work done to get this working on dotnet54.

### Approach
So far, there has been analysis completed on the nancy package to see what is/isn't available in the latest runtimes, and there are some areas that need replacing.
Due to the amount of work that needs doing, It's been suggested by @thecodejunkie that we try to get the project compiling first, then approach tests later on once we are happy and settled with the replacement code.

Most areas of the code should remain the same for the full CLR, and ifdefs should be used to swap out logic with comparable parts in the new environment.

### Why choose dotnet54 and not dnxcore50?
Dotnet54 is intended for use by microsoft by libraries and not the consuming applications, more information can be found here : aspnet/announcements#98

### Things that need tackling to get things compiling

- [x] Addition of dotnet54 to project.json file [@yantrio #2248]
- [x] Removal of SerializableAttribute (should be simple, but not sure on repercussions) [@yantrio #2255]
- [x] RNGCryptoServiceProvider -> RandomNumberGenerator.Create(), (this is currently what the Microsoft Identity packages use.) [@yantrio #2252]
- [x] BootstrapperException Ctor (SerializationInfo info, StreamingContext context), SerializationInfo isn't available, suitable replacement needed [@yantrio #2253]
- [x] DefaultObjectSerializer uses BinaryFormatter, it's not available, suitable replacement needed [@jchannon #2264]
- [x] Classes inheriting Stream need to use the suitable overrides, signatures have changed [@yantrio #2280 ]
- [x] Url class implements ICloneable, it's not available, is this an issue? [@yantrio #2251]
- [x] Most reflection needs tweaking/replacing. [@yantrio #2274]
- [x] CultureInfo caching (ie BuiltInCultureConventions class) needs replacing, suitable replacement needed [@jchannon #2258]
- [x] RijndaelEncryptionProvider makes use of RijndaelManaged class, not available. Replace or remove? (replace) [@yantrio #2254]
- [x] MemoryStream.GetBuffer is not available, suitable replacement needed [@yantrio #2249]
- [x] Uri.IsHexDigit/Uri.FromHex() is not available, suitable replacement needed. [@yantrio #2250]

### Things to note:
@khellang has asked for a list of packages and why we use them so we can try and trim the list of dependencies down, do we need some place to put this? maybe a wiki page in the long run?

**Comment by thecodejunkie** [comment]
> @khellang has asked for a list of packages and why we use them so we can try and trim the list of dependencies down, do we need some place to put this? maybe a wiki page in the long run?

This is a good thing to bring up in the description of each of the pull-requests

**Comment by khellang** [comment]
> RNGCryptoServiceProvider -> RandomNumberGenerator.Create()

I don't think there's a need to #ifdef anything here. The `RandomNumberGenerator.Create()` API is available on both `net451` and `dotnet5.4`

> RijndaelEncryptionProvider makes use of RijndaelManaged class, not available.

This can be replaced using the `Aes` class in the `https://www.nuget.org/packages/System.Security.Cryptography.Algorithms` package :+1:

> CultureInfo caching (ie BuiltInCultureConventions class) needs replacing

What does this mean? Are there any specific APIs that we use, that's not available?

> Uri.IsHexDigit/Uri.FromHex() is not available, suitable replacement needed.

Let's just rip the original implementations :smiling_imp: They're trivial. https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Private.Uri/src/System/Uri.cs#L1364-L1392

> MemoryStream.GetBuffer is not available, suitable replacement needed

If we can live with copying the data, let's just use `ToArray` here. Not sure where it's used.

> Most reflection needs tweaking/replacing.

This is mostly just a matter of adding in a `.GetTypeInfo()` call everywhere :dancers:

> Url class implements ICloneable, it's not available, is this an issue?

No, just :fire: it. If it's heavily used, we can keep the method, but :fire: the interface.

> Removal of SerializableAttribute
> BootstrapperException Ctor (SerializationInfo info, StreamingContext context)

These can easily be #ifdef'ed away, if we really need them, but in general, I think we should try to :fire: them :grin:

Just a couple of ¢ from me :wink:

**Comment by grumpydev** [comment]
Agree with most of what @khellang said, few notes:

As I said on the call, CultureInfo caching is the biggest concern I have - we put that in because the performance of doing it non-cached is stupid slow (like drop to 30 requests per second slow).

I cloneable I think we might use, but doing it without the interface is easy enough.

Bootstrapper exception - AFAIK this is the "best practice" way of making exception ctors, pretty sure we don't ever use that ctor so happy to nuke it :)

BinaryFormatter - can replace this with JSON once we have simple json in, although it's going to be a lot slower - surprised there isn't a replacement for this to be honest.

GetBuffer is (IIRC) a lot more efficient than ToArray so this is really going to nail perf when we have a stream switch I think.

The rest of the stream stuff is a reasonable chunk of work to switch over to using all the async methods, but it definitely something we need to do (along with update the response class)

**Comment by thecodejunkie** [comment]
Everything on the checklist is done, are the additional items we should be adding to it or shall we close this issue?

**Comment by phillip-haydon** [comment]
Woo that's awesome.

**Comment by jchannon** [comment]
I guess add whatever the remaining errors are?

**Comment by jchannon** [comment]
pinging @Yantrio

**Comment by Yantrio** [comment]
I think if @thecodejunkie is happy that we are compiling we can close this and open more issues if we need to futher down the line.

**Comment by thecodejunkie** [comment]
:+1:

**Comment by Yantrio** [comment]
WE DID IT GUYS! 

Closed
