### ISSUE TITLE
Migrate uses of AppDomainAssemblyTypeScanner to the new catalogs

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2221]
With the introduction of the new `IAssemblyCatalog` and `ITypeCatalog` (see #2217) we need to migrate the code to use these new types instead of the old (static) `AppDomainAssemblyTypeScanner`. We can use #1846 as a sort of reference as it was a spike for a similar approach. 

## Nancy
- [x] [NancyBootstrappeBase](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs) - Used to resolve all sorts of types that are going to be put into the container at startup (@TheCodeJunkie #2222)
- [x] [NancyInternalConfiguration](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyInternalConfiguration.cs) - This is the main consumer, the problem here is that is it being used from the static property [Default](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyInternalConfiguration.cs#L32). The class is used from the [InternalConfiguration](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L83) property on the NancyBoostrapperBase (@TheCodeJunkie #2225)
- [x] [Registrations](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/Registrations.cs) - It's used in a couple of helper methods. The `Registrations` instances are pulled from the container but the problem here is that we would have to enforce a ctor signature (something like `protected Registrations(ITypeCatalog catalog)`) and force all implementations to call it, so a major breaking change (@TheCodeJunkie #2240)
- [x] [NancyConventions](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Conventions/NancyConventions.cs) - Used to find the default conventions. Another issue is how we make use of the conventions. Currently we just create a new instance, of `NancyConventions` in [NancyBoostrapperBase.ctor](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L72) (@TheCodeJunkie #2231)
- [x] [DiagnosticsModuleCatalog](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Diagnostics/DiagnosticsModuleCatalog.cs#L61) - Used to find all `DiagnosticModule` instances and shoving them into the container. We manually create an instance of this in the [DiagnosticsHook.Enable](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Diagnostics/DiagnosticsHook.cs#L47) method. This should not be a problem because the way we call this method is from inside [DefaultDiagnostics](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Diagnostics/DefaultDiagnostics.cs#L80) which is an implementation of `IDiagnostics` and we pull that from the container already, so we just need to pass it down the chain. ( @jchannon #2226 )
- [x] [InfoModule](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Diagnostics/Modules/InfoModule.cs) - This is part of diagnostics and is a `DiagnosticModule`, so we can just add it to the ctor signature of the module, no worries ( @jchannon #2226 )
- [x] [SuperSimpleViewEngineRegistrations](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ViewEngines/SuperSimpleViewEngine/SuperSimpleViewEngineRegistrations.cs#L27) - Used to find all `ISuperSimpleViewEngineMatcher` and register them in the container. This should not be an issue because it is an implementation of `IRegistrations` and they are pulled from the container, so we should just be able to add the type catalog on the ctor ( @jchannon #2227 )
- [x] [ResourceAssemblyProvider](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ResourceAssemblyProvider.cs) - Is an implementation of `IResourceAssemblyProvider` that we stick into the container, from `NancyInternalConfiguration` so we can just add the catalog to the signature. **HOWEVER** It does not use ADATS for type discovery, it uses ADATS for **ASSEMBLY DISCOVERY** it grabs hold of all the loaded assemblies (the ones that ADATS loaded), that are not a Nancy-assembly. This breaks the signature we have for `ITypeCatalog` (new interface for this pull-request) because it currently only expose methods for grabbing types. (@TheCodeJunkie #2236)
- [x] [DefaultRuntimeEnvironmentInformation](https://github.com/NancyFx/Nancy/blob/d9ce213c9c8d8fe70d1e3b44686760c1475d676e/src/Nancy/DefaultRuntimeEnvironmentInformation.cs) - Straight forward change (@TheCodeJunkie #2238)
- [x] [NancyBootstrapperLocator](https://github.com/NancyFx/Nancy/blob/73cdb256308413ee8db8689c9836ea6963e02975/src/Nancy/Bootstrapper/NancyBootstrapperLocator.cs) - We use ADATS to find which Bootstrapper that should be used. Here we are faced with a chicken/egg problem because the `ITypeCatalog` lives inside the Bootstrapper. What we will be doing is remove the explicit use of ADATS and go straight to the `AppDomain`. When we make this CoreCLR compatible we will add in similar code for that target and wrap it in `#IFDEF` (@TheCodeJunkie #2246)
- [x] [AppDomainAssemblyTypeScanner](https://github.com/NancyFx/Nancy/blob/b74b76dc128ac6a4a2985677646e07d361766848/src/Nancy/Bootstrapper/AppDomainAssemblyTypeScanner.cs) - Kill it with :fire: (@TheCodeJunkie #2256) 

## Nancy.ViewEngines.Razor
- [x] Used to load in assemblies that you have defined in the web.config (@TheCodeJunkie #2241)
- [x] Used to discover model types (@TheCodeJunkie #2241)
- [x] Used to get assembly names when building up a descriptive error name when it could not find a model type (@TheCodeJunkie #2241)

## Nancy.Testing
- [x] [ConfigurableBootstrapper](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Testing/ConfigurableBootstrapper.cs) - Used in the [LoadReferencesForAssemblyUnderTest](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Testing/ConfigurableBootstrapper.cs#L157) method that tires to make sure that all assemblies are loaded that is going to be needed to run the test (it has to do with the whole problem we sometimes have where .net tries to be smart with removing unused references) (@TheCodeJunkie #2242)
- [x] [ConfigurableBootstrapper.Assembly](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Testing/ConfigurableBootstrapper.cs#L640) - Helper method used to force load assemblies for a test (@TheCodeJunkie #2247)

## Nancy.ViewEngines.Razor.Tests
- [x] Used in a test to ensure sure that an assembly is loaded (@TheCodeJunkie #2239)
- [x] Used in a test that ensures that a model can be found in that assembly (@TheCodeJunkie #2239)

## Nancy.Demo.Hosting.Aspnet
- [x] Used in a custom `IResourceAssemblyProvider` implementation. It's used to find all non dynamic assemblies. Again, this is another situation where ADATS is used to get assemblies instead of types (@jchannon #2224 )

## Nancy.Demo.Razor.Localiztion
- [x] Used in a custom `IResourceAssemblyProvider` implementation. It's used to find all non dynamic assemblies. Again, this is another situation where ADATS is used to get assemblies instead of types (@jchannon #2223 )

**Comment by khellang** [comment]
:clap: :dancers: :sparkles:
