### ISSUE TITLE
Upgrade coreclr branch to run on rc2

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2404]
## Checklist

- [ ] Update `build.ps1` to support `dotnet cli` instead of `dnx` (@TheCodeJunkie issue #2405, pull-request #2406)
- [x] Update `NuGet.config` to support the `https://www.myget.org/F/aspnetcidev/api/v3/index.json` feed (@TheCodeJunkie pull-request #2407)
- [ ] Update projects to support [netstandard1.3](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms) (including `#ifdef dotnet5_4` usages) (@TheCodeJunkie pull-request #2403)
- [ ] Update test projects to support `netcoreapp1.0` (replaces [netstandardapp1.5](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-standard-applications.md)) (instead of `dnxcore50`) and `net451` (instead of `dnx451`) (@TheCodeJunkie issue #2408)
- [ ] Update NuGet dependencies to rc2-versions (`1.0.0-*` until they lock them in as `-rc2`?)
- [ ] Update Nancy to run on the rc2 runtime (dependency model vs. library manager, `#ifdef DNX` and so on)
- [ ] Once everything runs fine on rc2 versions of CoreFX and CoreCLR, remove the rc1 specific stuff (TFM, Library Manager usage and so on)
- [ ] Remove all definitions and usages of the `DNX` compiler directive
- [ ] Verify that there are no rc1-artifacts remaining

## Projects that should be migrated

- Nancy
- Nancy.Authentication.Basic
- Nancy.Authentication.Forms
- Nancy.Authentication.Stateless
- Nancy.Embedded
- Nancy.Metadata.Modules
- Nancy.Testing

## Settings up the environment

The current Visual Studio tooling is build on top of DNX. In order to target rc2 builds, of CoreFX, you need to setup `dnvm` to support CI builds and pull down the latest rc2-build 

- `set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev/api/v2` (for OS X, use `export` instead of `set`)
- `dnvm upgrade -u`
- `dnvm upgrade -u -r coreclr`

Create a habit of updating the runtime daily to make sure you are on the latest all the time.

To run the code on the rc2 version of the runtime, you need to download and install the `Dotnet CLI` tools

- Download latest .NET Core SDK Installer ([x86](https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x86.latest.exe) | [x64](https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe))

The binaries are from https://github.com/dotnet/cli where you can also find the latest binaries for other platforms. Once installed, you get access to the `dotnet` command line tooling

> :information_source: If you get a warning that states _"You have installed 'Nightly`build of .NET Core CLI. It cannot be upgraded to a 'Release' build of .NET Core CLI. Please uninstall and re-run setup."_ then make sure you first remove all older installations of the Dotnet CLI.

**Comment by thecodejunkie** [comment]
It looks like we're going to have to resort to some `imports` for the main projects as well

```
\src\Nancy.Testing\project.json
    Package AngleSharp 0.9.5 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package AngleSharp 0.9.5 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl5 (Silverlight,Version=v5.0)
    Package System.Xml.XDocument 4.0.11-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Xml.XDocument 4.0.11-beta-23516 supports:

      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net45 (.NETFramework,Version=v4.5)
      - netcore50 (.NETCore,Version=v5.0)
      - win8 (Windows,Version=v8.0)
      - wp8 (WindowsPhone,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package Microsoft.Extensions.PlatformAbstractions 1.0.0-rc1-final is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package Microsoft.Extensions.PlatformAbstractions 1.0.0-rc1-final supports:
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - net451 (.NETFramework,Version=v4.5.1)
    Package System.Collections.Concurrent 4.0.11-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Collections.Concurrent 4.0.11-beta-23516 supports:
      - dotnet5.2 (.NETPlatform,Version=v5.2)
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net45 (.NETFramework,Version=v4.5)
      - netcore50 (.NETCore,Version=v5.0)
      - win8 (Windows,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Console 4.0.0-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Console 4.0.0-beta-23516 supports:
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net46 (.NETFramework,Version=v4.6)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Dynamic.Runtime 4.0.11-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Dynamic.Runtime 4.0.11-beta-23516 supports:
      - dnxcore50 (DNXCore,Version=v5.0)
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net45 (.NETFramework,Version=v4.5)
      - netcore50 (.NETCore,Version=v5.0)
      - win8 (Windows,Version=v8.0)
      - wp8 (WindowsPhone,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Net.NameResolution 4.0.0-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Net.NameResolution 4.0.0-beta-23516 supports:
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net46 (.NETFramework,Version=v4.6)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Net.Primitives 4.0.11-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Net.Primitives 4.0.11-beta-23516 supports:
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - dotnet5.2 (.NETPlatform,Version=v5.2)
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net45 (.NETFramework,Version=v4.5)
      - netcore50 (.NETCore,Version=v5.0)
      - win8 (Windows,Version=v8.0)
      - wp8 (WindowsPhone,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Reflection.TypeExtensions 4.1.0-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Reflection.TypeExtensions 4.1.0-beta-23516 supports:
      - dnxcore50 (DNXCore,Version=v5.0)
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net46 (.NETFramework,Version=v4.6)
      - netcore50 (.NETCore,Version=v5.0)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Runtime.Serialization.Primitives 4.1.0-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Runtime.Serialization.Primitives 4.1.0-beta-23516 supports:
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net45 (.NETFramework,Version=v4.5)
      - netcore50 (.NETCore,Version=v5.0)
      - win8 (Windows,Version=v8.0)
      - wp8 (WindowsPhone,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Security.Cryptography.Algorithms 4.0.0-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Security.Cryptography.Algorithms 4.0.0-beta-23516 supports:
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net46 (.NETFramework,Version=v4.6)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Security.Cryptography.X509Certificates 4.0.0-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Security.Cryptography.X509Certificates 4.0.0-beta-23516 supports:
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net46 (.NETFramework,Version=v4.6)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Threading.Thread 4.0.0-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Threading.Thread 4.0.0-beta-23516 supports:
      - dnxcore50 (DNXCore,Version=v5.0)
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net46 (.NETFramework,Version=v4.6)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    Package System.Xml.XmlSerializer 4.0.11-beta-23516 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Xml.XmlSerializer 4.0.11-beta-23516 supports:
      - dotnet5.1 (.NETPlatform,Version=v5.1)
      - dotnet5.4 (.NETPlatform,Version=v5.4)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net45 (.NETFramework,Version=v4.5)
      - netcore50 (.NETCore,Version=v5.0)
      - win8 (Windows,Version=v8.0)
      - wp8 (WindowsPhone,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    One or more packages are incompatible with .NETStandard,Version=v1.3.
```

**Comment by thecodejunkie** [comment]
Also looks like we need to switch from `netstandard1.3` to `netstandard1.4` because some of the CoreFX crypto packages recently changes to `netstandard1.4` http://stackoverflow.com/questions/35958696/error-building-aspnet-security-openidconnect-server/35959230#35959230
