### ISSUE TITLE
Migrate remaining projects to support netstandard 1.6

### ISSUE THREAD

**Issue by cemremengu** [NancyFx/Nancy#2606]
**Description**
---
We will need to update all Nancy packages/project to support netstandard 1.6. In order to achieve this, we may need to update the dependencies for some packages as well. If you need to update the dependencies do so by bumping it to the latest release that supports netstandard.

ℹ️ This task need to be completed **before** #2612.

**TODO**
---
(update this list including to link any pull-requests and **check** after merged or rejected)

### Main project
- [x] Nancy.Authentication.Basic (Up-to-date)
- [x] Nancy.Authentication.Forms (Up-to-date)
- [x] Nancy.Authentication.Stateless (Up-to-date)
- [x] Nancy.Embedded (Up-to-date)
- [x] Nancy.Encryption.MachineKey (Not supported on .NET Core)
- [x] Nancy.Hosting.Aspnet  (Not required)
- [x] Nancy.Hosting.Self  (Not required)
- [x] Nancy.Metadata.Modules  (Up-to-date)
- [x] Nancy.Owin  (Not required)
- [ ] Nancy.Validation.DataAnnotations
- [x] Nancy.Validation.FluentValidation  (Up-to-date)
- [ ] Nancy.ViewEngines.DotLiquid (#2599)
- [ ] Nancy.ViewEngines.Markdown  (#2614)
- [x] Nancy.ViewEngines.Nustache (Not supported on .NET Core)
- [x] Nancy.ViewEngines.Spark (Not supported on .NET Core)
- [x] Nancy.ViewEngines.Razor (Not supported on .NET Core)
- [x] Nancy.ViewEngines.Razor.BuildProviders (Not supported on .NET Core)

### Bootstrappers

- [x] Nancy.Bootstrappers.Autofac (Up-to-date)
- [x] Nancy.Bootstrappers.StructureMap  (Up-to-date)
- [x] Nancy.Bootstrappers.Ninject  (Not supported on .NET Core)
- [x] Nancy.Bootstrappers.Unity (Not supported on .NET Core)
- [x] Nancy.Bootstrappers.Windsor (Not supported on .NET Core)

### Serialization

- [x] Nancy.Serialization.JsonNet (Up-to-date)
- [ ] Nancy.Serialization.ProtBuf (https://github.com/NancyFx/Nancy.Serialization.ProtBuf/pull/28)
- [ ] Nancy.Serialization.ServiceStack (https://github.com/NancyFx/Nancy.Serialization.ServiceStack/pull/29)

**Valid rejection status for each of the projects**

- Up-to-date
- 3rd-party dependency does not support .NET Core
- Not supported on .NET Core
- Not required

Example

> - [x] Nancy.Foo (Not supported on .NET Core)
> - [x] Nancy.Bar (Up-to-date)
> - [ ] Nancy.Baz (pull-requests #9999)

**Comment by perlun** [comment]
Just a stupid question - netstandard16 meaning netstandard1.6, right?

**Comment by cemremengu** [comment]
@perlun Yes

**Comment by jchannon** [comment]
The sub repos are all done by default so you can remove those

**Comment by Sphiecoh** [comment]
I think `Nancy.Hosting.Self` can be removed. It will be replaced by Kestrel host.

**Comment by thecodejunkie** [comment]
@cemremengu can you please elaborate on this PR a bit more? What does "bump all to latest" mean? All what?
And do we have projects that target netstandard, just not 1.6? 

Please maintain this list and link the PRs for each project

**Comment by thecodejunkie** [comment]
Here's a sample of an Epic https://github.com/NancyFx/Nancy/issues/2000

**Comment by thecodejunkie** [comment]
The categories "packages" and "subrepos" confuses me a bit. They're all packages

**Comment by thecodejunkie** [comment]
Me again 😄 

I need this issue to 

* _clearly_ describe the purpose and scope
* link to pull-requests that are sent in order to help close this
* descriptive information why some aren't needed: like (already updated), (dependency does not support netstandard yet) and so on
* have a clear description of how 3rd party dependencies will be bumped. Are we staying withing the minor or are we also considering bumping the major?

**Comment by Sphiecoh** [comment]
`Bootstrappers.Ninject` needs to be marked as rejected since it depends on `Ninject.Extensions.ChildKernel` which is not supported on core
