### ISSUE TITLE
Update testing infrastructure

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2612]
## Description

We need to overhaul the test infrastructure, in the Nancy test projects, and make sure they all run the same version of xunit. We also need to bump the used version of FakeItEasy and re-enable all our tests on .NET Core. 

## Pre-requisits

Complete the migrations detailed in #2606 "Migrate remaining projects to support netstandard 1.6"

## Required steps

1. Update the xunit dependency in all `packages.config` to version `2.2.0-beta2-build3300` (this it the version we currently use in `project.json)
2. Ensure all `project.json` really use `2.2.0-beta2-build3300`
3. Update all `Nancy.*.Tests` projects to use FakeItEasy `2.3.1` (waiting for confirmation by @adamralph that this is the version we need for .NET Core)
4. Re-enable all tests for .NET Core

ℹ️ There is no need to bump the version of `dotnet-test-xunit`, for `project.json`, because we are already running the latest (`2.2.0-preview2-build1029`)

## TODO
(up this list and link any pull-requests that are sent to address the above)

- [x] Nancy.Authentication.Basic.Tests (pull-request #2705)
- [x] Nancy.Authentication.Forms.Tests (pull-request #2713)
- [ ] Nancy.Embedded.Tests (pull-request #2713 updates FIE and xunit, and adds netappcore1.0 tests, **but does not run latter on Unix**)
- [x] Nancy.Encryption.MachineKey.Tests (pull-request #2713 updates FIE and xunit; Nancy.Encryption.MachineKey does not have .NET Standard target)
- [x] Nancy.Hosting.Aspnet.Tests (pull-request #2713 updates FIE and xunit; Nancy.Hosting.Aspnet does not have .NET Standard target)
- [x] Nancy.Hosting.Self.Tests (pull-request #2713 updates FIE and xunit; Nancy.Hosting.Self does not have .NET Standard target)
- [x] Nancy.Metadata.Modules.Tests (pull-request #2713)
- [x] Nancy.Owin.Tests (pull-request #2713 updates FIE and xunit; Nancy.Owin does not have .NET Standard target)
- [x] Nancy.Testing.Tests (pull-request #2713)
- [x] Nancy.Tests.Functional (pull-request #2713 updates xunit)
- [x] Nancy.Tests (pull-request #2634)
- [x] Nancy.ValidationDataAnnotations.Tests (pull-request #2713 updates FIE and xunit; Nancy.Validation.DataAnnotations does not have .NET Standard target)
- [x] Nancy.Validation.FluentValidation.Tests (pull-request #2713)
- [x] Nancy.ViewEngines.DotLiquid.Tests (pull-request #2713 updates FIE and xunit; Nancy.ViewEngines.DotLiquid does not have .NET Standard target)
- [x] Nancy.ViewEngines.Markdown.Tests (pull-request #2713 updates FIE and xunit; Nancy.ViewEngines.Markdown does not have .NET Standard target)
- [x] Nancy.ViewEngines.Razor.Tests (pull-request #2713 updates FIE and xunit; Nancy.ViewEngines.Razor does not have .NET Standard target)
- [x] Nancy.ViewEngines.Spark.Tests (pull-request #2713 updates xunit; Nancy.ViewEngines.Spark does not have .NET Standard target)

ℹ️ Only send a pull-requests **once you have confirmed that all the required steps (above) have been satisfied** 

### Valid rejection status for each of the projects

- Up-to-date
- 3rd-party dependency does not support .NET Core
- Not supported on .NET Core

Example

> - [X] Nancy.Foo (Not supported on .NET Core)
> - [X] Nancy.Bar (Up-to-date)
> - [X] Nancy.Baz (pull-requests #9999)

**Comment by blairconrad** [comment]
> Update all `Nancy.*.Tests` projects to use FakeItEasy 2.3.1

@thecodejunkie, the FakeItEasy packages on NuGet.org do not support .NET Core. The packages that target .NET Standard 1.6 can only be had from our [AppVeyor feed](https://ci.appveyor.com/nuget/FakeItEasy).
As I type

* FakeItEasy 2.4.0-netstd-build000034 and 
* FakeItEasy.Analyzer 2.4.0-netstd-build000034

are available. I think they'll meet your needs.

**Comment by thecodejunkie** [comment]
@blairconrad thanks for the update. Do you have an ETA of the packages on NuGet.org? Ideally I'd like to avoid yet another package source, unless it's months away

**Comment by blairconrad** [comment]
@thecodejunkie, unfortunately we do not.
We won't be able to publish "production" versions until Castle.Core releases a non-beta version, and it's not clear when that's coming.
There are also a few small things that we should sort out internally before we release a production version, such as (minor) differences in the available functionality in the .NET Core and .NET Regular FakeItEasy libraries. Also, we currently only have unit tests and API-conformance tests available for the .NET Core build: no integration or acceptance tests.

I understand your reluctance to add another package source, but had I to suggest a path today, I'd add it.

**Comment by thecodejunkie** [comment]
@blairconrad after a short twitter exchange with @jonorossi it seems they were waiting on FakeItEasy, while you have been waiting on them. Maybe we can resolve this dead-lock? 😄

**Comment by jonorossi** [comment]
> until Castle.Core releases a non-beta version, and it's not clear when that's coming.

@blairconrad I had no idea you guys were waiting on a "stable" release, I was actually waiting on the 3 mocking libraries to have betas on nuget.org before going with a final release, especially that we made changes in beta002 for FakeItEasy. How did the AdditionalAttributes changes work out, did everything work well.

This is actually the first time someone has asked me for an non-prerelease build.

**Comment by jonorossi** [comment]
When I say a "beta" on nuget.org, I just meant any pre-release end users could try things out, especially since the Castle.Core package dependency gets exposed rather than ILMerged on .NET Core. Moq and NSubstitute have had alpha/beta/rc for a while.

**Comment by jonorossi** [comment]
@blairconrad there wasn't really a discussion anywhere around this since I'm the only one driving the Castle ship, I've commented on the last remaining issue about deferring it until post-v4, but got no response so no one watching Castle Core had an opinion.

I just thought it was a good idea to make sure all 3 mocking frameworks ship fully working in case we need to make breaking changes like beta002. If you want me to skip ahead without a FakeItEasy pre-release on nuget.org, then I'm okay with that.

**Comment by blairconrad** [comment]
@jonorossi, I didn't comment on castleproject/Core#201 because I have no interest in the log4net integration, so I didn't want to butt in.

Thanks for thinking of us mockers. The FakeItEasy owners have just had a conversation and we're going to work on a 3.0-prerelease (with .NET Standard support) for NuGet.org.

We don't have a firm date (of course), but it should be soon enough that @thecodejunkie can wait to use the NuGet.org package pre-release package, and also for @jonorossi to wait on it for the Castle.Core 4.0 release. That is days, not weeks, before the pre-release package appears on NuGet.org.

**Comment by jonorossi** [comment]
> I didn't comment on castleproject/Core#201 because I have no interest in the log4net integration, so I didn't want to butt in.

That issue was never in the v4 milestone, I assume you were thinking about the NLog not having a non-prerelease package one (https://github.com/castleproject/Core/issues/200). We'll just downgrade NLog and remove .NET Core to ship Castle Core with only the Serilog adapter working on .NET Core, until NLog and log4net get their releases sorted.

> That is days, not weeks, before the pre-release package appears on NuGet.org.

Great, I'd be happy to cut the 4.0.0 final once Nancy has updated to that package, would be a good test with such a large codebase verifying FakeItEasy.

I know it isn't the best way to run an OSS project but don't assume I've actually got plans for Castle releases, everything has been reactive based on what people want, just log an issue or ping me if you guys need something, I'll do my best to find the time to get what you need done.

**Comment by blairconrad** [comment]
Yeah, we don't map out the releases either.
Fix bugs as reported (when we can), maybe work on a feature that looks fun when it occurs to us. Release whenever (preferably soon). Were it not for the desire to make breaking changes somewhat infrequently, I think there'd be no plan at all!

Thanks for the offer, and your continued work!

**Comment by blairconrad** [comment]
@jonorossi, @jchannon, in case you missed it, FakeItEasy 3.0.0-alpha001 is out. I've done _no_ testing outside our usual release process, but if I find time today, will see if I can hook it up to NancyFx. Or vice versa.

https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.0.0-alpha001

**Comment by blairconrad** [comment]
I'm still asleep. Don't know why I put @jchannon in there when I meant @thecodejunkie. Apologies to whichever of you is most offended.

**Comment by jchannon** [comment]
I am offended beyond belief sir. I will see you at dawn for a dual.

**Comment by adamralph** [comment]
A duel would be more traditional.

**Comment by jchannon** [comment]
I blame the Github UI it cut off "carriageway drag race"

**Comment by adamralph** [comment]
👍 makes sense. I was thinking that you probably meant that, being more progressive than traditional.

**Comment by blairconrad** [comment]
Unless I'm misinterpreting, this issue is "grab a project, add a more modern .NET Core-supporting framework section to it, and make the darn thing run", no?
I can't promise fast progress, and I've made some extremely dubious changes, but for netcoreapp1.0, I've accomplished

```
=== TEST EXECUTION SUMMARY ===
Nancy.Tests  Total: 1814, Errors: 0, Failed: 1, Skipped: 0, Time: 40.687s
```

Which I feel is somewhat encouraging. If I'm actually doing something that's desired, I'll whip up a super rough PR in (my) morning.

**Comment by blairconrad** [comment]
An update: [FakeItEasy-3.0.0-beta002](https://www.nuget.org/packages/FakeItEasy/3.0.0-beta002-build000066) has been released to NuGet.
I use it in #2634, which passes, including running the Nancy.Tests tests under netcoreapp1.0 on both Windows and Unix. 

@NancyFx/owners, I know everyone's busy, and I don't mean to push, but is there something I've missed before the PR can be reviewed? (I am convinced you'll want changes, which I'm happy to make.)

@jonorossi, I think that even without the changes to the PR, we've an indication that FakeItEasy can perform well in the context of the project. Does provide enough support for you to go ahead with the Castle.Core 4.0.0 release?

**Comment by jonorossi** [comment]
@blairconrad yep thanks, will get it sorted in the next couple of days.

**Comment by blairconrad** [comment]
Thanks, @jonorossi. No particular rush, but wanted to know whether I was holding things up. 🐳

**Comment by jonorossi** [comment]
Apologies for the delay, Castle Core 4.0.0 final is available: http://www.castleproject.org/blog/2017/01/25/core-4.0.0-release/

/cc @blairconrad, @thomaslevesque

**Comment by thomaslevesque** [comment]
> Apologies for the delay, Castle Core 4.0.0 final is available: http://www.castleproject.org/blog/2017/01/25/core-4.0.0-release/

Awesome, thanks @jonorossi!

**Comment by blairconrad** [comment]
Yes! Thanks, @jonorossi!

**Comment by thecodejunkie** [comment]
Sorry for dropping the ball on this (work/life stuff). What is needed from Nancy. Code review? Anything else? Can we perhaps create a checklist in https://github.com/NancyFx/Nancy/pull/2634 of things that are needed so we can start ripping into it? 😍

**Comment by blairconrad** [comment]
@thecodejunkie, work and life happen. Don't worry. Assuming I've understood this whole issue, I think the next step is a review of #2634. I've surely done some things that are not correct or in keeping with Nancy's style. Where I'm aware of them, I've made notes in the review. I'm happy to change anything - no comment is too petty! But until I get some feedback from Team Nancy, I don't know what to adjust.

**Comment by blairconrad** [comment]
#2634 (I think) qualifies to check the "Nancy.Tests" box way upstairs.
And I've begun #2705 for "Nancy.Authentication.Basic.Tests".

**Comment by blairconrad** [comment]
Assuming #2713 is acceptable, I think the list upstairs could be updated to something like the following (I did not trace down whether components' 3rd-party requirements supported .NET Core or not; if the production project didn't have a .NET Standard project, I just stopped there).

- [x] Nancy.Authentication.Basic.Tests (pull-request #2705)
- [x] Nancy.Authentication.Forms.Tests (pull-request #2713)
- [ ] Nancy.Embedded.Tests (pull-request #2713 updates FIE and xunit, and adds netappcore1.0 tests, **but does not run latter on unix**)
- [x] Nancy.Encryption.MachineKey.Tests (pull-request #2713 updates FIE and xunit; Nancy.Encryption.MachineKey does not have .NET Standard target)
- [x] Nancy.Hosting.Aspnet.Tests (pull-request #2713 updates FIE and xunit; Nancy.Hosting.Aspnet does not have .NET Standard target)
- [x] Nancy.Hosting.Self.Tests (pull-request #2713 updates FIE and xunit; Nancy.Hosting.Self does not have .NET Standard target)
- [x] Nancy.Metadata.Modules.Tests (pull-request #2713)
- [x] Nancy.Owin.Tests (pull-request #2713 updates FIE and xunit; Nancy.Owin does not have .NET Standard target)
- [x] Nancy.Testing.Tests (pull-request #2713)
- [x] Nancy.Tests.Functional (pull-request #2713 updates xunit)
- [x] Nancy.Tests (pull-request #2634)
- [x] Nancy.ValidationDataAnnotations.Tests (pull-request #2713 updates FIE and xunit; Nancy.Validation.DataAnnotations does not have .NET Standard target)
- [x] Nancy.Validation.FluentValidation.Tests (pull-request #2713)
- [x] Nancy.ViewEngines.DotLiquid.Tests (pull-request #2713 updates FIE and xunit; Nancy.ViewEngines.DotLiquid does not have .NET Standard target)
- [x] Nancy.ViewEngines.Markdown.Tests (pull-request #2713 updates FIE and xunit; Nancy.ViewEngines.Markdown does not have .NET Standard target)
- [x] Nancy.ViewEngines.Razor.Tests (pull-request #2713 updates FIE and xunit; Nancy.ViewEngines.Razor does not have .NET Standard target)
- [x] Nancy.ViewEngines.Spark.Tests (pull-request #2713 updates xunit; Nancy.ViewEngines.Spark does not have .NET Standard target)

The only outstanding item that I can see is [running the .NET Core App Nancy.Embedded.Tests on Unix](https://github.com/NancyFx/Nancy/pull/2713#issue-212617189), and I have hit a wall there.

**Comment by horsdal** [comment]
Updated described from @blairconrad comment

**Comment by thecodejunkie** [comment]
@horsdal you just beat me to merging #2713 and now updating this list! 👍 

@blairconrad super thanks!

**Comment by blairconrad** [comment]
@thecodejunkie, a pleasure.
